### ISSUE TITLE
Would you accept a PR for an assembly based boot and implementation of SystemInit?

### ISSUE THREAD

**Issue by jeffreyabecker** [Spritetm/hc32l110-gcc-sdk#1]
I've been playing around with the slightly larger HC32L110C6UA-SFN20TR chip and have a working boot loader in assembly and SystemInit implementation. Would you want this code contributed?

**Comment by jeffreyabecker** [comment]
never-mind I the overall size difference between the hand-coded and C versions was like 10 instructions so ::shrug::

**Comment by Spritetm** [comment]
Still, thanks for willing to contribute. Sorry not to respond to your PR earlier btw, it slipped my mind.

**Comment by jeffreyabecker** [comment]
I mean would you want me to submit a PR for the DDL I'm writing? IDK if you've tried to use theirs but I'm very much not a fan.

**Comment by Spritetm** [comment]
I can entirely imagine you're not a fan and I may certainly use yours if I'm ever gonna use this chip for something more than a blinkie. However, given the fact that I don't have any current plans for doing anything with it and I'd like to keep my maintainer workload low, can I advise you to start your own repo? If it's anywhere near working, I'd be happy to put a link in the readme of this repo; I can imagine we're not the only ones who prefer to use something else than the manufs stuff.

**Comment by jeffreyabecker** [comment]
Right now I've validated:

   - boot/isv (thanks to your code),
   - clock configuration,
   - systick (may expand on this)
   - peripheral enable/disable


I've also worked on but not validated:

   - basic timers,
   - capture/compare/pwm (PCA in their docs)
   - spi
   - i2c,
   - realtime clock
